apiVersion: v1
kind: Pod
metadata:
  name: nodejs
spec:
  containers:
  - name: nodejs
    image: node:8
    imagePullPolicy: Always
    command: [ "tail", "-f", "/dev/null" ]
    tty: true
    volumeMounts:
      - name: ssh-volume
        mountPath: /root/.ssh
      - name: npm-secret
        mountPath: /root/.npmrc
        subPath: .npmrc
  volumes:
    - name: ssh-volume
      secret:
        secretName: ssh-config
        defaultMode: 256
    - name: npm-secret
      secret:
        secretName: npm-secret
